version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: fitness_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1313
      POSTGRES_DB: fit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
